# Generated by Django 3.0.5 on 2020-04-02 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_test_age'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table='tb_heros',
        ),
    ]
