# Generated by Django 3.0.5 on 2020-04-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20200402_1252'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table=None,
        ),
    ]
