# Generated by Django 3.0.5 on 2020-04-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_auto_20200402_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='age',
        ),
        migrations.AlterModelTable(
            name='test',
            table='testmodel_test',
        ),
    ]
