# Generated by Django 3.0.5 on 2020-04-02 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_auto_20200402_1307'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table=None,
        ),
    ]
